# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca0c613cfa91671effcd553808596a642c207dea2c64ccca847b1f081b17aace66898dc9423e3d7e20bfcd4eb6188105ec5fbf9befbf3b1a5e72260a8384aef

test:
  secret_key_base: 364681f828082af6c0cce19dc4cade69ebb7b3f53f4aeadb619bc1cd815fd0dfa23f9117e6fb3fb0c6f73aea0e337c6736909a0fe1fa6d6332b63d4e6d5c94a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
